# Tasca M3 T01

## Ejercicios con Numpy


## Ejercicio 1

### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

Para este primer ejercicio, he creado una función que imprime la media, la mediana, la desviación estándar, la varianza y los valores máximos y mínimos. 

In [2]:
import numpy as np

arrr=np.array([1,3,1,4,3])

def analisisarray(x):
    if x.ndim>1:
        return "Error - Más de una dimensión"
    else:
        media = x.mean()
        mediana = np.median(x)
        desviacion =  x.std()
        varianza = np.var(x)
        maxx = max(x)
        minn = min(x)
        print ("La media es {}".format(media))
        print ("La mediana es {}".format(mediana))
        print ("La desviación estándar es {}".format(desviacion))
        print ("La varianza es {}".format(varianza))
        print ("El valor máximo es {} y el mínimo es {}".format(maxx,minn))
        
    
analisisarray(arrr)

La media es 2.4
La mediana es 3.0
La desviación estándar es 1.2
La varianza es 1.44
El valor máximo es 4 y el mínimo es 1


## Exercici 2

### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

Para este ejercicio, he fijado una semilla para que los resultados sean replicables (aunque dependiendo del objetivo no sería necesario fijar nada)

Así mismo, he indicado que los elementos contenidos en el array serán números enteros, aunque eso podría cambiarse en el caso de que se quisieran números decimales u otro tipo de elementos. 

In [4]:
from numpy import random
import numpy as np

np.random.seed(123) 

def cuadradogenerate(N):
    arrayvacio = np.array([], dtype="i") 
    for i in range(N**2):
        x = random.randint(100)
        arrayvacio = np.append(arrayvacio, x)
    arrayvacio = arrayvacio.reshape(N, N)
    return arrayvacio
        
cuadradogenerate(4)

array([[66, 92, 98, 17],
       [83, 57, 86, 97],
       [96, 47, 73, 32],
       [46, 96, 25, 83]])

## Exercici 3

### Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

En este caso, he asumido que con "totales" se refieren a los resultados de las sumas de todos los valores de cada fila y cada columna. 

Para generar una tabla de dos dimensiones he utilizado una función similar a la del apartado anterior, pero con ligeras modificaciones. 

Por último, propongo dos opciones distintas: en una primera opción, la función "printea" los resultados de las sumas de las filas y las columnas. No obstante, también he pensado una segunda opción en la cual los resultados se guardan en arrays 2D, en los cuales la primera fila indica los números de fila o columna analizados (0,1,2...) y en la segunda fila se muestran los sumatorios. 

En ambas opciones, incluyo un "return" para devolver los arrays y dar la opción a que esos valores puedan ser utilizados posteriormente

In [33]:
import numpy as np

np.random.seed(123)

#En un primer lugar, genero un array MxN con números aleatorios: 

def arraygenerate(N,M):
    arrayvacio = np.array([], dtype="i") #
    for i in range(N*M):
        x = random.randint(100)
        arrayvacio = np.append(arrayvacio, x)
    arrayvacio = arrayvacio.reshape(N, M)
    return arrayvacio

aaa=arraygenerate(3,2)
print(aaa) #Compruebo que la matriz se genera correctamente

#Empezamos con la primera opción (la más sencilla):

def calculototals(ar):
    sumascolumnas = ar.sum(0)
    sumasfilas = ar.sum(1)
    print("Las sumas de las filas son {}".format(sumasfilas))
    print("Las sumas de las columnas son {}".format(sumascolumnas))
    return sumascolumnas, sumasfilas
            
columnas1, filas1 = calculototals(aaa)

print(filas1) #array 1D con los sumatorios de cada fila
print(columnas1) #array 2D con los sumatorios de cada columna

[[66 92]
 [98 17]
 [83 57]]
Las sumas de las filas son [158 115 140]
Las sumas de las columnas son [247 166]
[158 115 140]
[247 166]


In [31]:
def calculototalss(ar):
    dim=np.shape(ar)
    indexfilas = np.array(range(dim[0]))
    indexcolumnas = np.array(range(dim[1]))
    sumasfilas = ar.sum(1)
    sumascolumnas = ar.sum(0)
    resfil=np.stack((indexfilas,sumasfilas), axis=0)
    rescol=np.stack((indexcolumnas,sumascolumnas), axis=0)
    print("En esta primera tabla, podemos ver el número de filas (fila 1) y su respectiva suma (fila 2):")
    print(resfil)
    print("En esta segunda tabla, podemos ver el número de columnas (fila 1) y su respectiva suma (fila 2):")
    print(rescol)
    return resfil, rescol

filas11, columnas11 = calculototalss(aaa)
print (filas11) #Aquí tendré el array con los datos de las filas
print (columnas11) #Aquí tendré el array con los datos de las columnas


En esta primera tabla, podemos ver el número de filas (fila 1) y su respectiva suma (fila 2):
[[  0   1   2]
 [158 115 140]]
En esta segunda tabla, podemos ver el número de columnas (fila 1) y su respectiva suma (fila 2):
[[  0   1]
 [247 166]]
[[  0   1   2]
 [158 115 140]]
[[  0   1]
 [247 166]]


## Exercici 4

### Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

Para este ejercicio, he definido una función que permite calcular el coeficiente de correlación de Pearson. Este coeficiente de correlación no depende de la escala de las medidas, y es ampliamente utilizado para realizar análisis estadísticos. El valor oscila entre -1 y +1: Si el valor es negativo, indica que cuando una variable incrementa la otra disminuye (correlación negativa). Por el contrario, si el valor obtenido es positivo, indica que ambas variables incrementan (correlación positiva). Un valor cercano al 0 indica que la correlación es débil o inexistente, siendo 1 o -1 indicativos de correlaciones perfectas.



In [34]:

import numpy as np
import math 

def calculocorrelacion(x,y):
    if x.ndim>1 or y.ndim>1:
        return "Error - Solo se acepan arrays de 1 dimensión" #Limitamos el uso de la función a arrays de 1D
    if len(x) != len(y):
        return "Error - Ambos arrays deben tener la misma longitud" #Se solicitan dos inputs de la misma longitud
    else:
        mediax=x.mean()
        mediay=y.mean()
        arriba=0
        deno1=0
        deno2=0
        for i in range(len(x)): #Loop para cada uno de los puntos del array
            arriba+=((x[i]-mediax)*(y[i]-mediay))
            deno1+=(x[i]-mediax)**2
            deno2+=(y[i]-mediay)**2
        deno1raiz=math.sqrt(deno1)
        deno2raiz=math.sqrt(deno2)
        coefpearson=arriba/(deno1raiz*deno2raiz)
        coefpearsonround=round(coefpearson,3) #Redondeamos el resultado
        return coefpearsonround

x=np.array([1,2,3])
y=np.array([1,2,3])

calculocorrelacion(x,y)

1.0